In [ ]:
import numpy as np
a=np.array([10,12,13,14])
print(a)
b=np.array([[10,12,13],[14,15,16]])
print(b)
print(a.ndim)
print(b.ndim)
print(a[1])
print(b[0,1])
print(a[-1])
print(a[2:5])
print(a[:3])
print(b[0:2,2:4])
print(b.shape)

[10 12 13 14]
[[10 12 13]
 [14 15 16]]
1
2
12
12
14
[13 14]
[10 12 13]
[[13]
 [16]]
(2, 3)


In [ ]:
n=np.array([1,2,3,4,5,6])
print(n.reshape(2,3))
print(n.reshape(3,2))
for x in n:
  print(x)
n1=np.array([7,8,9])
n2=np.concatenate((n,n1))
print(n2)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
1
2
3
4
5
6
[1 2 3 4 5 6 7 8 9]
